### ISSUE TITLE
Policy point

### ISSUE THREAD

**Issue by linxuyalun** [tass-io/scheduler#15]
一个是进程的 scale up 和终止，应该是 `pkg/runner/fnscheduler/fnscheduler.go` 这个文件下的 Refresh 方法

一个是 shceudler 下一个函数优先选择本地进程还是必须跨网络以及本地是否有资源继续创建这个进程，这个 policy 的设置应该是在 middleware 的部分。这个部分主要是为了体现测试局部性的重要性。

本地是否可以创建进程，这个应该是由 fnscheduler 这一部分进行处理的。这里需要的原因是为了测试可以让进程禁止本地的创建从而全走网络

预启动模型相关的 policy。另外，`pkg/runner/fnscheduler/fnscheduler.go` 这里 fnScheduler 进行新 process 的调度的时候一个有一个 policy 决定调度的时机。 我理解这里 fnScheduler 应该有一个地方去放置这个预启动模型的策略部分，但是我并没有找到类似的一个时间点。只有看到一个 canCreate 的函数，但是没有找到一个何时创建这个 process 的函数

目前想到以上这些，如有更新我再补充

**Comment by tx19980520** [comment]
> 一个是进程的 scale up 和终止，应该是 `pkg/runner/fnscheduler/fnscheduler.go` 这个文件下的 Refresh 方法

你这里提到的 scale up 这 scale up 我目前没感受到其需要什么策略，这应该属于是最终的决策。shutdown process 这里将会涉及使用策略对于已有的 process 进行选择，选择的结果是 instance 状态的改变。

> 一个是 shceudler 下一个函数优先选择本地进程还是必须跨网络以及本地是否有资源继续创建这个进程，这个 policy 的设置应该是在 middleware 的部分。这个部分主要是为了体现测试局部性的重要性。

这个部分实际上已经有原型实现，即现在static middleware, 这里将会考虑重新设计一下方式来方便你启动和关闭middleware

> 本地是否可以创建进程，这个应该是由 fnscheduler 这一部分进行处理的。这里需要的原因是为了测试可以让进程禁止本地的创建从而全走网络

这个部分现在就是 return true，可设计的内容比较少，因为你要是想拿到其他的info，我感觉都得去问一些单例或者是去问系统，你具体想要什么默认实现呢。

> 预启动模型相关的 policy。另外，`pkg/runner/fnscheduler/fnscheduler.go` 这里 fnScheduler 进行新 process 的调度的时候一个有一个 policy 决定调度的时机。 我理解这里 fnScheduler 应该有一个地方去放置这个预启动模型的策略部分，但是我并没有找到类似的一个时间点。只有看到一个 canCreate 的函数，但是没有找到一个何时创建这个 process 的函数

预启动模型，具体的实现应该是一个 event source, 你现在可以看到，static/lsds middleware 都有产生 event 的能力，那你的预启动模型不管怎么收集其他信息的，最终的形式都是以  event 的形式给出，交由下游处理的。

**Comment by linxuyalun** [comment]
> 你这里提到的 scale up 这 scale up 我目前没感受到其需要什么策略，这应该属于是最终的决策。shutdown process 这里将会涉及使用策略对于已有的 process 进行选择，选择的结果是 instance 状态的改变， 这里考虑的默认实现是 request 没处理完全的存量最少者

这个 scale up 是说根据请求负载量或者是这个进程的压力去做的 scale up，然后这个 shutdown 还要考虑的一个因素是 TTL

> 这个部分现在就是 return true，可设计的内容比较少，因为你要是想拿到其他的info，我感觉都得去问一些单例或者是去问系统，你具体想要什么默认实现呢。

这样就可以了，info 的具体需求根据情况再看

**Comment by tx19980520** [comment]
> 这个 scale up 是说根据请求负载量或者是这个进程的压力去做的 scale up，然后这个 shutdown 还要考虑的一个因素是 TTL

这个部分实际还是实现一个上游 event，可以考虑后续设计， shutdown 这里默认将会添加一个时间戳在创建时来计算
