### ISSUE TITLE
[Scheduler] Draft of cluster-level schedule

### ISSUE THREAD

**Issue by linxuyalun** [tass-io/scheduler#4]
The policy of Pod level auto-scaling, which contains:

* The main idea of a process created in another Pod
* How to collect Pod metrics? `pprof` or Prometheus? Their advantages & disadvantages?  A draft is needed.

**Comment by KONY128** [comment]
-----------THIS IS A DRAFT!----------


# Pod 级别的水平扩容模块

### Pod 级别水平扩容模块的设计动机

**设计动机**

1. Tass 中每个 workflow 在逻辑上是相互隔离的，因此，Tass 系统将不同的 workflow 运行于不同的 pod 中，保证 workflow 之间的隔离性。在这样的设计里，不同 workflow 的 pod 有可能会被 k8s 控制面协调到同一个节点上，从而导致它们之间的相互影响。在请求高负荷的场景下，一个 workflow 很可能抢占其他同节点的 workflow 资源，此时，被抢占资源的 workflow 需要及时的水平扩展，否则被抢占者的吞吐量和延时会被迫变差，影响性能。Tass 系统要尽量避免这样的相互影响。
2. 「未扩展完」单 workflow 自己面对高负载时需要扩容

综上所述，Tass 系统具有水平扩容 Pod 的需求，需要有相应的系统与设计为之服务。

**设计诉求**

 「未扩展完」尽量使用 K-Native 的方式

- 原生方式可以保证 k8s 集群性能指标参数获取和传输、存储的安全性
- 原生方式可以避免 k8s 集群与自编写的中心化或分布式组件协调、同步、控制所带来的额外性能开销
- 原生方式可以增强策略的易理解性与语义可解释性
- 减少水平扩容模块的复杂性

### Pod 级别水平扩容模块系统设计

##### Metrics 收集与分析

 「未扩展完」

##### Pod 扩容策略与实现

 「未扩展完」

1. workflow 的资源占用标定
    1. 基于先验统计的初始值预估策略
    2. 基于历史的 MLP 推断资源占用
2. Global 层次的扩容策略
3. Local 层次的扩容策略

### Pod 级别水平扩容模块的总结

 「未扩展完」

**Comment by KONY128** [comment]
## 必须尽快决定的决策性问题

### Pod 水平扩展做还是不做

- **这个部分的设计和编程实现比较棘手**
 
  我们学习和上手各种工具和接口需要时间。而且这部分要想做出彩，难度不比论文的核心模块实现简单。我们很可能不得不对各种工具和接口深入了解，进行高度定制化。

  经过我的仔细查询，各种定制化的诉求没有太多的现成资料，可行性暂时未知，不确定投入的时间会不会是无底洞。

  我会尽快尝试原型实现，对各种方案的可行性做尝试。

  以下举例一些可能需要深入了解的内容：

  可能需要对以下内容定制化：

  - metrics-server、Prometheus、Kubernetes scheduler、Kubernetes aggregate layer

  可能需要深入以下接口：

  - Kubernetes Metrics API、Prometheus QL

  如果要避免整个集群顶不住压力返回 500，可能需要弄一个消息队列进行流量削峰

- **想要验证这部分实现比较困难**。

  要想模拟多 workflow 的场景需要精心设计，编码难度高。更糟的是，很难做实验说明这些对 Pod 调度和水平扩展的设计是高效的。

  每一个策略的实现代价都有未知数，如果弄好几套策略实现来做实验对比，我们会在这个模块的开发上付出过多时间；

  如果和成熟的云厂商对比，别人的策略和环境对于我们是未知的，而且云厂商很可能是硬堆节点，何况代码不开源，我们很难在云厂商上模拟有限资源的场景，也很难对实验结果进行理论分析；

  就算我们对标开源 Serverless 平台，其调度的粒度是运行在 Pod 内的单个 Function，这种调度和扩展的资源需求是固定的，可预测的，它们的实现难度和复杂性都比我们的系统小很多

  我预估**传统架构下，调度节点和水平扩展上的表现大概率比 Tass 这种资源需求不确定的系统快**，我们在策略上做的心思再多，实验的效果很可能没有别人好，如履薄冰

---

### 如果决定做，要做到多好？

- **要把这个模块做出彩，性价比较低**
  
  要做出彩，很可能一个人在 6 周内搞不定设计、实现、验证、书写的工作。
  
  我们必须尽快梳理论文中已经确定的章节，梳理有哪些可选内容，**尽快确定该模块在论文中所占的比重**，优先完成高性价比的章节。
  以下选择需要敲定：

  - 模块只作为论文一个小点，保证 workflow 有最基本的扩容能力和兜底能力，保证多 workflow 下可接受的最小鲁棒性和正确性，避免讨论性能和实验，目的只为应付答辩提问，强调扩容与调度并非本文的核心，这些是未来需要展开的工作，操作起来相对简单

  - 模块保证多 workflow 下的高吞吐量和低延时，保证高负载下集群的高效运转，作为一大亮点，仔细做实验进行验证，操作起来难度较大

- **如果不打算做过于细节的对比实验和结果论证，考不考虑节省一些编程实现**？
 
  可不可以在论文上多叙述一些思路和方法，节省一些编程上的过于复杂的实现，在实验中体现策略有效果即可？

**Comment by KONY128** [comment]
> 可以润色后写进论文里的一些论述

# Pod 级别的水平扩容系统

### 系统设计动机与核心

**设计动机**

Tass 中每个 workflow 在逻辑上是相互隔离的，因此，Tass 系统会将不同的 workflow 运行于不同的 Pod 中，保证 workflow 之间的隔离性。不同 workflow 的 Pod 有可能会被 k8s 控制面协调到同一个节点上，它们之间可能会相互影响。在 workflow 处理请求的过程中，可能会遭遇以下问题：

1. 一个 workflow 在处理请求时：

   1. Pod 所处物理机的 CPU 与内存资源已被耗尽，无法进一步提供资源供给新启动的 function 进程
   
   2. 该 workflow 处于高负载中，无法正常处理来临的请求，其开始出现响应时间提升，丢失请求甚至进程崩溃的情况
   
2. 在高负荷的请求下，一个 workflow 很可能抢占同节点其他 workflow 的资源，此时，被抢占资源的 workflow 需要及时的水平扩展，避免吞吐量的下降和延时的提升，保证性能。

要想解决上述问题，Tass 系统就必须具有水平扩容 Pod 的能力。

下文将提出相应的系统与策略为之服务。

**设计核心**

本系统在 Metrics 的收集、扩容的请求上都尽量以 K-Native 的方式实现，这是考虑了以下优点：

- 原生方式可以保证 k8s 集群性能指标参数获取和传输、存储的安全性

- 原生方式可以避免 k8s 集群与自编写的中心化或分布式组件协调、同步、控制所带来的额外性能开销

- 原生方式可以增强策略的易理解性与语义可解释性

- 减少水平扩容模块的复杂性

由于 Tass 系统具有 function 的 Keep-alive 策略，水平扩容系统遵循以下原则：水平扩容的优先级高于 Keep-alive 节点的回收。这是考虑以下内容：

- 如果优先回收，很难保证所回收的 function 短时间内不会再次调用，落地这样的策略实现往往比较困难

- Keep-alive 能力是减少冷启动时间的重要特性，现实中厂商也遵循上述原则，常常会部署大量的机组保证该特性有效。

  >  Keep-alive 的时间需要根据集群的负载动态调整，这不是本系统优化的重点

Tass 系统在下述特例下，会根据历史主动回收调用概率低的 Keep-alive function：

- 水平扩容请求连续失败超过两次

- 扩容请求 timeout

### Pod 级别水平扩容模块系统设计

**Metrics 收集与分析**

 「见楼下的具体策略」

**Pod 扩容策略与实现**

 「见楼下的具体策略」

**Comment by KONY128** [comment]
>【此楼为旧方案，废弃，需要讨论或者了解细节请与我联系】
>
>【可以略过本楼，此楼内容只作为个人总结备忘录】
>
>实现：global metrics 和 local metrics，相当于自己实现一套 Auto-scaler，需要扩容就向 controller update replica
>
>难度：5/5
>
>好处：
>
>1. 可以做出花来，让水平扩展策略高度匹配 Tass 系统，做大量的实验和图表
>
>2. 扩容的响应时间肯定是最短的，因为是阻塞的通知机制而非轮询机制
>
>坏处：
>
>1. 自己弄一套 Auto-scaler 实现很复杂，要去手动对接 Prometheus（Global Metrics 调度组件）、Istio（在 Local Scheduler 中的 Local Metrics 模块） 的接口，拿到资源占用率和每秒负载量。在 HPA 验证搞不定后再来考虑这个方案
>
>2. 存在 Time of check to time of use 问题。很可能是多个 LS 向 Api-server 发送 update 扩容请求。比如：如果有三个 LS，replica 的 update 事件在 Delta FIFO 中可能同一时间有：更新成 4，更新成 4，更新成 5 的要求（书写顺序不代表实际存储顺序），controller reconcile 的先后顺序可能会引发一些麻烦的状况
>
>3. 我们并不存在一个中心化的调度组件，这让 global metrics 难以发挥作用。global metrics 了解各个 node metrics 的目的就是为了尽量让因扩容需求新起的 pod 运行在不同的 node 上，经过历史预估 workflow pod 的资源占用，采用贪婪的方式让每个 node 上资源负载越少越好（类似闪存磨损均衡算法）。这样在最开始的 schedule 过程里就避免了后续 scale up 的可能性。如果要改动，必须去改 k8s scheduler（虽然现在 scheduler 是 12 阶段可插拔的，但是我没改过，不知道改起来会不会蛋疼）
>
>4. 整个系统语义不清晰，实验不好做，系统不好验证是不是高效的（直觉上我感觉肯定比 HPA 高效，但是不好抽离其他影响直接作比较）

### Pod 级别水平扩容模块系统设计

**Metrics 收集与分析**

【可行性未定，暂不书写成正文】

Local Metrics：

> 补充：为什么弃用 ``pprof``？
>
> ``pprof`` 自身会占用一份不可忽视比例的 CPU 资源（约 25% ）和内存资源（每个进程约 80M），且内存资源的占用无法由 ``pprof`` 自身感知，代价比较大，还不准，debug 用还行，每个进程都用会吃不消

因为每个 function 的资源占用是已知的（用户指定的），所以 local scheduler 分配的 Cgroup 是确定的，local scheduler 自己知道各个 function 有多少个进程在跑，所以可以比较精确、快速地拿到 Pod 占用资源的值

Global Metrics：

1. 选用 metrics-server ：自定义 aggregate layer；重设定 CPU占用与内存占用的语义

2. 选用 Prometheus：每个节点资源占用聚合值；80-80 特殊的指标聚合值（见后文）

**Pod 扩容策略与实现**

【可行性未定，暂不书写成正文】

从 workflow runtime 中获取 workflow 的资源占用值

1. workflow runtime 的资源占用值标定

   1. 基于先验统计的初始值预估策略

   2. 基于历史的 MLP 推断资源占用
   
2. Global 层次的扩容策略（关注调度，新来的 Pod 尽量 “磨损均衡”）

3. Local 层次的扩容策略（关注扩容兜底与启发式扩容，要拿到负载值自己负责扩容（实际上自己负载高了很容易卡死，感觉不可行），如果本地申请资源失败要扩容，请求来不及处理要转发出去，得关注 TTL 和 timeout）（另一种方式：因为有文献支撑，workflow 中最长调用链一般不超过 5 个，且遵循 2-8 法则，因此可以考虑已经有 8 个 function 在运行过后（有 3 个作缓冲空间），再启动新的 function 则启动下一个 Pod（但是为了更好的利用 locality，还是兜底好一点））

4. 在超过 80% 的节点的内存资源占用超过 80% 时，启动积极的 Keep-alive 回收策略（能不能让 Keep-alive 回收策略可以调参，让它），进一步避免整个集群被卡死（可选）

其他略

**Comment by KONY128** [comment]
>实现：基于 HPA、Prometheus（可选）与 Prometheus-adapter、Istio（可选）、Victoria Metrics（可选）
>
>难度：
>
>1. 1/5（不要普罗米修斯、Istio，写死 Pod CPU Memory 占用阈值，部署最简单的 Metrics-server；去 Ingress 中拿到 route 的每秒请求数，这个每秒请求数可以测几个 workflow 之后写死）
>
>2. 3.5/5（使用 Prometheus 和 Istio，获取更精确和更细致的指标，可以有更多骚操作，比如熔断等）
>
>3. 4/5 （使用 Victoria Metrics 避免 Prometheus 单点查询性能瓶颈）
>
>好处：
>
>1. K-native
>
>2. 实现相较简单
>
>3. Local Scheduler 和 Operator 不需要做太多更改，代码侵入性较小
>
>坏处：
>
>1. 论文里把这部分写出花的难度相对较大
>
>2. 响应时间和性能比不上自己实现的的 Auto-scaler，因为 HPA 机制是轮询性能指标（秒为单位），并且这些指标有持久化开销以及网络开销
>
>关键点：
>
>1. 建议将 HPA 轮询性能指标时间从默认的 15s 缩短到默认 1~2s，并且支持用户指定
>
>2. HPA 的 Pod 扩缩容上下限建议由用户指定，不设默认值

### Pod 级别水平扩容模块系统设计

**Metrics 收集与分析**

【由于方案未定，暂不书写成正文】

1. 选择 metrics-server ：仅（也仅能）监控 CPU、内存、Ingress 各路径每秒请求值

2. 选择 Prometheus 和 Istio：每个 Pod 的 CPU 内存指标，每个 node 的 CPU 内存指标

**Pod 扩容策略与实现**

【由于方案未定，暂不书写成正文，只写最缩略的方案】

【我先搞个下面的简单版本试试可行性，可行再弄复杂的】

扩容实现基于 HPA

需要说明：Pod 扩缩容上下限、HPA 轮询性能指标时间

1. 兜底：若 Pod 创建新的 function 进程失败，则尝试进行本地资源的回收（见本项备注）。则 LS 向 controller 发起 scale-up （update 事件），并将请求和数据缓存到 redis 中。轮询等待 scale up 后尝试将请求和数据转发给新的 Pod 进行后续运算和处理。

   > 请求新进程失败说明资源已经见底了，这时候可能 LS 可能都无法继续执行，比如 append()、copy() 等基础操作都没有内存可以 alloc 了，所以最好先回收一下资源。
   >
   > 疑问：需要消息队列或者 reschedule 吗？

2. 指标：HPA 会根据 k8s-Prometheus-adapter 以及 Istio 的以下指标尝试进行 Pod 扩展：

   1. 每个 workflow 的总 QPS 是否达到新的台阶
   
   2. 每个 workflow 的平均心跳响应时间是否大于某阈值

**Comment by KONY128** [comment]
> 备忘录，记录一些可能有用的知识以及不错的文章

---

Metrics-server：

> 只能监控到 Pod 的 CPU 和内存占用，可扩展性不强，但是部署起来和使用起来最简单

HPA：

[知乎：探索 Kubernetes HPA](https://zhuanlan.zhihu.com/p/89453704)

Victoria Metrics：

[Prometheus 水平扩展方案（二）：Victoria Metrics 学习、试用](https://www.lijiaocn.com/%E9%A1%B9%E7%9B%AE/2020/02/24/prometheus-scale-out-2.html)

> 补充：啥是 Victoria Metrics？
>
> Victoria Metrics 本质是一个支持水平扩展的时序数据库，可以作为 Prometheus 的远端存储，避免 Prometheus 自带存储单点查询故障。
>
> 我们的实验和假设中，集群中只有 Tass 在运行，多 workflow 可能会有多个 HPA 对 Prometheus 自带存储进行固定时长的轮询。
>
> 理论上 workflow 数量非常多的时候会影响查询效率，但是我估计实验最多做 2 - 4 个 workflow 并发的情况，而且很难确定这一点会不会是瓶颈
>
> 【结论：在 auto-scaler 的基本架子没有搭起来时，暂时不做考虑】

**Comment by linxuyalun** [comment]
非常感谢！整体内容很充实，辛苦了！

麻烦后续在我们整体方案确定后将这部分内容更新到 doc 的 repo 中

**Comment by linxuyalun** [comment]
“Pod 级别水平扩容模块系统设计” 这部分你分成两个模块概述，我理解这两种方案大方向都没有问题。

但是首先我想我们先达成一些共识，再去讨论这两个方案的选择以及更细节的方案

1. 目标是什么？
为了体现 serverless 本身的自动响应的特点，由于这部分内容是所有 FaaS 一定会提供的。从论文的角度来说，核心的论述角度是“问题是什么？缺点是什么？我是怎么优化的？” Auto-scale 是 serverless 的一个优点，而不是这部分的缺陷或者是一个亟待优化的地方。所以策略的实现更多是适配 Tass 的一种 auto-scale，而不是说需要做到特别出彩。从这个角度，我倾向于更简单清晰的解决方案。
2. 调度本身的问题。
这里我理解有一块地方和你的思路不一样的地方，我觉得可以拎出来讨论一下。我们的调度方案其实本质是一个两级调度，一个是全局调度，一个本地调度。全局调度做的事情是 pod-level 的，本地调度是 process-level 的。我们假设你已经通过全局获取了每个节点的资源占用了。那么 pod 这一层的扩容应该是由这个全局的调度器下发的。我们明确一下本地调度器和全局调度器的职责：本地调度器启动进程，进程创建不起来的时候往其他 Pod 发送；全局调度器启动 Pod，它只关注全局资源的视角。所以，从我的角度，本地调度器最好对全局调度透明，它只负责创建进程，如果说本地资源不够就扔到其他 Pod，如果发现其他 Pod 不行，那就等待一段时间后再尝试，如果还是无法发送数据，那是说明资源不够了。进一步的说，全局调度器要比本地调度器有更低的阈值，从而在本地调度器满载之前先一步创建好 Pod。这里一定会存在的问题是，会存在 Pod 创建晚于本地调度器的需求，这里我们不做考虑，而是希望保证架构和模型本身的清晰。
3. 具体的算法？
时间关系，我暂时没办法太具体这部分的想法，我大约会在晚上进一步跟进，直觉上说，我希望这个全局调度的启发式算法能够根据每个节点的 wf 数量判定一个扩展的时机。举个简单的例子，一个 node 有两个 wf，然后节点是 2CPU 4GB，然后通过咱们的启发式算法得到说这两个 wf 预计各吃 1 个 CPU 和 2GB，然后扩展时机就是在某个 wf 吃掉 1.5GB 的时候就触发扩展。

**Comment by linxuyalun** [comment]
@KONY128 @tx19980520

**Comment by linxuyalun** [comment]
如有任何问题以及所有需要帮助的地方，随时和我联系

**Comment by tx19980520** [comment]
>   如果要避免整个集群顶不住压力返回 500，可能需要弄一个消息队列进行流量削峰

这里感觉还是要具体的描述具体的压力，虽然收集手段不同，但是从信息的层面实际是完全一样的，应该多一些描述

>   要想模拟多 workflow 的场景需要精心设计，编码难度高。更糟的是，很难做实验说明这些对 Pod 调度和水平扩展的设计是高效的。

我没有对下文进行阅读，从我的理解，最好的验证方式还是QOS的验证，这里倒是可以参考下serverlessbench的相关characters

>   每一个策略的实现代价都有未知数，如果弄好几套策略实现来做实验对比，我们会在这个模块的开发上付出过多时间；

>   就算我们对标开源 Serverless 平台，其调度的粒度是运行在 Pod 内的单个 Function，这种调度和扩展的资源需求是固定的，可预测的，它们的实现难度和复杂性都比我们的系统小很多

我怎么觉得从最外层的角度而言，我们的性能一定比开源Serverless好，至少比 OpenWhisk 好，而且还有很多开源平台的底座都不是k8s。

>   我预估**传统架构下，调度节点和水平扩展上的表现大概率比 Tass 这种资源需求不确定的系统快**，我们在策略上做的心思再多，实验的效果很可能没有别人好，如履薄冰

能不能具体说一下 tass 哪里比别人差了。

> ### 如果决定做，要做到多好？
> * **要把这个模块做出彩，性价比较低**
>   要做出彩，很可能一个人在 6 周内搞不定设计、实现、验证、书写的工作。
>   我们必须尽快梳理论文中已经确定的章节，梳理有哪些可选内容，**尽快确定该模块在论文中所占的比重**，优先完成高性价比的章节。
>   以下选择需要敲定：
>   
>   * 模块只作为论文一个小点，保证 workflow 有最基本的扩容能力和兜底能力，保证多 workflow 下可接受的最小鲁棒性和正确性，避免讨论性能和实验，目的只为应付答辩提问，强调扩容与调度并非本文的核心，这些是未来需要展开的工作，操作起来相对简单
>   * 模块保证多 workflow 下的高吞吐量和低延时，保证高负载下集群的高效运转，作为一大亮点，仔细做实验进行验证，操作起来难度较大
> * **如果不打算做过于细节的对比实验和结果论证，考不考虑节省一些编程实现**？
>   可不可以在论文上多叙述一些思路和方法，节省一些编程上的过于复杂的实现，在实验中体现策略有效果即可？

这个部分的观点比较认可，因为是为了毕业，有的地方只要make sense 和测试不会测到一般就裂开就可以了。

**Comment by tx19980520** [comment]
> Tass 系统在下述特例下，会根据历史主动回收调用概率低的 Keep-alive function：
> 
> * 水平扩容请求连续失败超过两次
> * 扩容请求 timeout

这个地方是strategy 还是 policy，以及谁去触发扩容请求，这个触发方在 tass operator 还是哪里，local scheduler 是需要如何才能知道 operator 的这项决议呢，是何种形式下发该决议呢。

**Comment by tx19980520** [comment]
> > 2. 响应时间和性能比不上自己实现的的 Auto-scaler，因为 HPA 机制是轮询性能指标（秒为单位），并且这些指标有持久化开销以及网络开销
Pod 级别需要那么迅速的 scale 吗，阿里云现阶段函数冷启动一个函数大概是2s。
另外的一个问题是，我需要知道 scale down 的时候的 graceful shutdown， 你们这边打算怎么处理。

> 1. 兜底：若 Pod 创建新的 function 进程失败，则尝试进行本地资源的回收（见本项备注）。则 LS 向 controller 发起 scale-up （update 事件），并将请求和数据缓存到 redis 中。轮询等待 scale up 后尝试将请求和数据转发给新的 Pod 进行后续运算和处理。
谁是 controller，redis的目的是什么，是为了削峰吗？
这里的一个骚操作是这样的，我的毕设里面的操作是如果没找到具体的instance，直接redirect 给ingress，ingress那边去block到存在实例或者return timeout，即LS 本身不和 controller 打交道，唯独是 ingress 跟中心打交道，少去很多削峰的可能。

>    > 请求新进程失败说明资源已经见底了，这时候可能 LS 可能都无法继续执行，比如 append()、copy() 等基础操作都没有内存可以 alloc 了，所以最好先回收一下资源。
没内存了可能就不是我自己回收了，是被 OOM kill了，这里感觉都轮不到我 LS 去做事情

**Comment by tx19980520** [comment]
ingress 的部分我们甚至没有什么考虑，但是上文多次提及，这里特意提出，以及之前提出的pprof的问题，can you share any blogs or our experience?
